### ISSUE TITLE
Wind speed and temperature

### ISSUE THREAD

**Issue by raphaeldavid** [bbernstein/homebridge-snowswitch#5]
Would it be possible to create switches, one that activates with a specified wind speed and one with a specified temperature, always with Dark Sky?
Thank,

**Comment by bbernstein** [comment]
This probably would be pretty easy. I think there are some projects out there that have more general weather info. I've moved this project to [using "sensors" instead of switches](https://github.com/bbernstein/homebridge-snowsense) so that you can have more control over how to react to the changes in the status.

Feel free to fork/copy the project [homebridge-snowsense](https://github.com/bbernstein/homebridge-snowsense) and give it some more flexibility for things like temperature and wind speed. I don't know if I'll have much time to add features like that right now, but I'm happy to review and help with it if you're new to programming in javascript or coding in general.
